// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCalendarAccount = "calendar_account"

// CalendarAccount mapped from table <calendar_account>
type CalendarAccount struct {
	ID    int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Login string `gorm:"column:login;not null" json:"login"`
	Email string `gorm:"column:email;not null" json:"email"`
}

// TableName CalendarAccount's table name
func (*CalendarAccount) TableName() string {
	return TableNameCalendarAccount
}
