// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMeetingStatus = "meeting_status"

// MeetingStatus mapped from table <meeting_status>
type MeetingStatus struct {
	ID   int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name string `gorm:"column:name;not null" json:"name"`
}

// TableName MeetingStatus's table name
func (*MeetingStatus) TableName() string {
	return TableNameMeetingStatus
}
