// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProject = "project"

// Project mapped from table <project>
type Project struct {
	ID                 int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Theme              string `gorm:"column:theme;not null" json:"theme"`
	Year               int32  `gorm:"column:year;not null" json:"year"`
	SupervisorID       int32  `gorm:"column:supervisor_id;not null" json:"supervisor_id"`
	StudentID          int32  `gorm:"column:student_id;not null" json:"student_id"`
	StatusID           int32  `gorm:"column:status_id;not null" json:"status_id"`
	RepoID             int32  `gorm:"column:repoId" json:"repoId"`
	CloudDriveFolderID string `gorm:"column:cloud_drive_folder_id;not null" json:"cloud_drive_folder_id"`
}

// TableName Project's table name
func (*Project) TableName() string {
	return TableNameProject
}
