// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProjectStage = "project_stage"

// ProjectStage mapped from table <project_stage>
type ProjectStage struct {
	ID   int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name string `gorm:"column:name;not null" json:"name"`
}

// TableName ProjectStage's table name
func (*ProjectStage) TableName() string {
	return TableNameProjectStage
}
