// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRepositoryAccount = "repository_account"

// RepositoryAccount mapped from table <repository_account>
type RepositoryAccount struct {
	ID    int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Login string `gorm:"column:login;not null" json:"login"`
	Email string `gorm:"column:email;not null" json:"email"`
}

// TableName RepositoryAccount's table name
func (*RepositoryAccount) TableName() string {
	return TableNameRepositoryAccount
}
