// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRepository = "repository"

// Repository mapped from table <repository>
type Repository struct {
	ID    int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name  string `gorm:"column:name;not null" json:"name"`
	Owner string `gorm:"column:owner;not null" json:"owner"`
}

// TableName Repository's table name
func (*Repository) TableName() string {
	return TableNameRepository
}
