// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameStudent = "student"

// Student mapped from table <student>
type Student struct {
	ID         int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name       string `gorm:"column:name;not null" json:"name"`
	Surname    string `gorm:"column:surname;not null" json:"surname"`
	MiddleName string `gorm:"column:middle_name;not null" json:"middle_name"`
	UniGroup   string `gorm:"column:uni_group;not null" json:"uni_group"`
}

// TableName Student's table name
func (*Student) TableName() string {
	return TableNameStudent
}
