// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTaskStatus = "task_status"

// TaskStatus mapped from table <task_status>
type TaskStatus struct {
	ID   int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name string `gorm:"column:name;not null" json:"name"`
}

// TableName TaskStatus's table name
func (*TaskStatus) TableName() string {
	return TableNameTaskStatus
}
