// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTask = "task"

// Task mapped from table <task>
type Task struct {
	ID                 int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name               string    `gorm:"column:name;not null" json:"name"`
	Description        string    `gorm:"column:description;not null" json:"description"`
	Deadline           time.Time `gorm:"column:deadline;not null" json:"deadline"`
	StatusID           int32     `gorm:"column:status_id;not null" json:"status_id"`
	ProjectID   	   int32     `gorm:"column:project_id;not null" json:"project_id"`
	ProjectStageID     int32     `gorm:"column:project_stage_id;not null" json:"project_stage_id"`
	CloudDriveFolderID string    `gorm:"column:cloud_drive_folder_id;not null" json:"cloud_drive_folder_id"`
}

// TableName Task's table name
func (*Task) TableName() string {
	return TableNameTask
}
