// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProjectStatus = "project_status"

// ProjectStatus mapped from table <project_status>
type ProjectStatus struct {
	ID   int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name string `gorm:"column:name;not null" json:"name"`
}

// TableName ProjectStatus's table name
func (*ProjectStatus) TableName() string {
	return TableNameProjectStatus
}
